import mongoose from 'mongoose';

const plaidTransactionSchema = new mongoose.Schema({
  account_id: String,
  account_owner: String,
  amount: Number,
  authorized_date: Date,
  authorized_datetime: Date,
  category: String,
  category_id: String,
  check_number: Number,
  counterparties: [{
    confidence_level: String,
    entity_id: String,
    logo_url: String,
    name: String,
    phone_number: String,
    type: String,
    website: String,
  }],
  date: Date,
  datetime: Date,
  iso_currency_code: String,
  location: {
    address: String,
    city: String,
    country: String,
    lat: Number,
    lon: Number,
    postal_code: String,
    region: String,
    store_number: String,
  },
  logo_url: String,
  merchant_identity_id: String,
  merchant_name: String,
  name: String,
  payment_channel: String,
  payment_meta: {
    by_order_of: String,
    payee: String,
    payer: String,
    payment_method: String,
    payment_processor: String,
    ppd_id: String,
    reason: String,
    reference_number: String,
  },
  pending: Boolean,
  pending_transaction_id: String,
  personal_finance_category: {
    confidence_level: String,
    detailed: String,
    primary: String,
    version: String
  },
  personal_finance_category_icon_url: String,
  transaction_code: String,
  transaction_id: { type: String, unique: true },
  transaction_type: String,
  unofficial_currency_code: String,
  website: String,
});

export default mongoose.model('plaid_transactions', plaidTransactionSchema);
